% obj is the main testbench object
% --- build up a fluidic pump ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013
% Modified by Pavel Kulik - Nov 2013

function obj = pump_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
stringBoxSize = [0.5, 0.15];
pushButtonSize = [0.175, 0.2];
editBoxSize = [0.15, 0.15];

% pump panel
obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel = uipanel(...
    'Parent', parentObj, ...
    'Unit','Pixels', ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Pump', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

x_start = 0.05;
y_start = 0.8;

% start button
obj.gui.(parentStruct)(panelIndex).fldPumpUI.startButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.05, .8, pushButtonSize], ...
    'String','Start', ...
    'Callback', {@start_button_callback, obj, parentStruct, panelIndex});

x_align = x_start + 0.25;
y_align = y_start;

% stop button
obj.gui.(parentStruct)(panelIndex).fldPumpUI.stopButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Stop', ...
    'Callback', {@stop_button_callback, obj, parentStruct, panelIndex});

x_align = x_align + 0.25;

% purge button
obj.gui.(parentStruct)(panelIndex).fldPumpUI.purgeButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Purge', ...
    'Callback', {@purge_button_callback, obj});

x_align = x_align + 0.25;

% settings button
obj.gui.(parentStruct)(panelIndex).fldPumpUI.settingsButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Settings', ...
    'Callback', {@settings_button_callback, obj, parentStruct, panelIndex});

y_align = y_start - 0.35;
x_align = x_start;

% flowRate string
obj.gui.(parentStruct)(panelIndex).fldPumpUI.flowRateString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, stringBoxSize], ...
    'String','Flow Rate(uL/min) =', ...
    'FontSize', 8);

x_align = x_align + 0.25;

% flowRate number
obj.gui.(parentStruct)(panelIndex).fldPumpUI.flowRateEdit = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, editBoxSize], ...
    'String', 10);
%     'Callback', {@flowRate_string_cb, obj});

x_align = x_align + 0.2;

% pumping string
obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpingString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, stringBoxSize(1)/2, stringBoxSize(2)], ...
    'String','Pumping:', ...
    'FontSize', 8);

x_align = x_align + 0.2;

% pumping active indicator
obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpingIndicator = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'BackGroundColor', [1, 0, 0], ...
    'Visible', 'on', ...
    'Enable', 'off', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, .05, .15]);

% set color indicator if already on...
if obj.instr.pump.Busy % is already on
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpingIndicator, ...
            'BackgroundColor', [0, 1, 0]); % make display box green
end

x_align = x_start;
y_align = y_align - 0.35;

% update volume push button
obj.gui.(parentStruct)(panelIndex).fldPumpUI.volumeUpdateButton = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','pushbutton', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, 0.3, 0.2], ...
    'String','Update Pumped Vol', ...
    'FontSize', 8,...
    'Callback', {@update_volume_button_cb, obj, parentStruct, panelIndex});

x_align = x_align + 0.325;
y_align = y_align - 0.025;

% % update volume string
% obj.gui.(parentStruct)(panelIndex).fldPumpUI.volumeUpdateString = uicontrol(...
%     'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
%     'Style','text', ...
%     'BackgroundColor',[0.9 0.9 0.9 ], ...
%     'HorizontalAlignment','left', ...
%     'Units', 'normalized', ...
%     'Position', [x_align, y_align, stringBoxSize], ...
%     'String','Update Volume:', ...
%     'FontSize', 8);
% 
% x_align = x_align + 0.325;
% y_align = y_align - 0.025;
% 
% % update volume checkbox
% obj.gui.(parentStruct)(panelIndex).fldPumpUI.volumeUpdateCheck = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
%     'Style', 'checkbox', ...
%     'BackgroundColor', [0.9, 0.9, 0.9], ...
%     'Enable', 'on', ...
%     'Units', 'normalized', ...
%     'Position', [x_align, y_align, pushButtonSize], ...
%     'Callback', {@auto_update_volume_cb, obj, parentStruct, panelIndex});
% 
% x_align = x_align + 0.1;
% y_align = y_align + 0.025;

% pumped volume string
obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpedVolumeString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, stringBoxSize], ...
    'String','Pumped Vol(uL):', ...
    'FontSize', 8);

x_align = x_align + 0.2;

% pumped volume edit
obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpedVolumeDisp = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldPumpUI.mainPanel, ...
    'Style','text', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, editBoxSize], ...
    'String', 0);
%    'Callback', {@volume_disp_cb, obj, parentStruct, panelIndex});

% update the pumped volume value
update_volume_button_cb([], [], obj, parentStruct, panelIndex)

end

%% Callback Functions
%     function flowRate_string_cb(hObject, ~, obj)
%         % set the pumped flowRate, should be in uL/min
%         new_vel = str2double(get(hObject, 'String'));
%         obj.instr.pump.setParam('flowRate', new_vel);
%     end

%     function volume_disp_cb(obj, parentStruct, panelIndex)
%         pumped_vol = round(obj.instr.pump.getPumpedVolume * 10) / 10;
%         set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpedVolumeDisp,...
%             'String', num2str(pumped_vol));
%     end
    
    function update_volume_button_cb(~, ~, obj, parentStruct, panelIndex)
        pumped_vol = round(obj.instr.pump.getPumpedVolume * 10) / 10;
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpedVolumeDisp,...
            'String', num2str(pumped_vol));
    end

    function start_button_callback(~, ~, obj, parentStruct, panelIndex)
        % start pump
        obj.instr.pump.start;
        % change indicator to green
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpingIndicator, 'BackgroundColor', [0, 1, 0]);
        % set pump flow rate in the gui
        flowRate = obj.instr.pump.getParam('FlowRate_uLpMin');
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.flowRateEdit, 'String',...
            num2str(flowRate));
    end

    function stop_button_callback(~, ~, obj, parentStruct, panelIndex)
        % stop pump
        obj.instr.pump.stop;
        % update volume pumped display
        pumped_vol = obj.instr.pump.getPumpedVolume;
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpedVolumeDisp, 'String', num2str(pumped_vol));
        % change indicator to red
        set(obj.gui.(parentStruct)(panelIndex).fldPumpUI.pumpingIndicator, 'BackgroundColor', [1, 0, 0]);
    end

    function purge_button_callback(~, ~, obj)
        % purge the pump lines
        obj.instr.pump.purge;
    end

    function settings_button_callback(~, ~, obj, parentStruct, panelIndex)
        obj.instr.pump.settingsWin;
    end

%     function auto_update_volume_cb(hObject, ~, obj, parentStruct, panelIndex)
%         isChecked = get(hObject, 'Value');
%         if isChecked
%             obj.timer.pumpVolumeTimer = timer(...
%                 'Name', 'Pump-Update-Timer', ...
%                 'ExecutionMode', 'fixedRate', ...
%                 'BusyMode', 'drop', ...
%                 'Period', obj.instr.pump.getParam('UpdatePeriod'), ...
%                 'TimerFcn', {@volume_disp_cb, obj, parentStruct, panelIndex});
%             start(obj.timer.pumpVolumeTimer);
%         else
%             stop(obj.timer.pumpVolumeTimer);
%             delete(obj.timer.pumpVolumeTimer);
%         end
%    end