function defaultStruct = assayParamsDefault()

defaultStruct = struct(...
...%'UseFastILEngine', false,.. **Propertities no longer used in the software
...%'DisableStageActiveFB', false, ... **
    'SavePlots', false,...
    'OptimizeSweepRange', false,...
    'ZeroDetectors', false,...
    'ZeroTSL', false,...
    'TranslateRecipeTimeToSweeps', false,...
    'WaitForTempStabilization', true,...
    'WaitForTempTimeout_min', 5,...
    'TempComparisonPrecision', 3,...
    'TempComparisonTolerance', 0.005, ...
    'TubeInID_um', 510,...
    'TubeInLength_mm', 180,...,
    'PrimeFluidicChannel', false,...
    'PrimeFluidicChannelVelocity_uLpMin', 0,...
    'SequenceReagentsManually', false,...
    'StopPumpDuringScan', false,...
    'RelaxPressureTime_sec', 0,...
    'ReversePumpTimeAtReagentChange', 0,...
    'ScansUntilNextFineAlign', 10,...
    'RecipeIterations', 1,...
    'AssayIterations', 1);
end