function changeRecipePopup(obj)

numOfReagent = length(obj.recipe.reagent);
w = 0.10;
h = 0.06;
x = 0.05;

recipeSettingMain = figure(...
    'Visible', 'off', ...
    'Menu', 'None', ...
    'Name', 'Change Recipe', ...
    'NumberTitle', 'off', ...
    'Units', 'normalized', ...
    'Position', [0 0 .41 .61]);

uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Reagents', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 1.5*w, 0.04]);

x = x+1.5*w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Well#', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 0.8*w, 0.04]);

x = x+0.8*w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Time(min)', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 1.2*w, 0.04]);

x = x+1.2*w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'RI', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 0.8*w, 0.04]);

x = x+0.8*w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Velocity', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, w, 0.04]);

x = x+w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Temp(C)', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 1.1*w, 0.04]);

x = x+1.1*w+0.01;
uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'text', ...
    'BackGroundColor', [0.8, 0.8, 0.8], ...
    'String', 'Comment', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [x, 0.91, 2.2*w, 0.04]);

doneButton = uicontrol(...
    'Parent', recipeSettingMain, ...
    'Style', 'pushbutton', ...
    'BackGroundColor', [0.9, 0.9, 0.9], ...
    'String', 'Done', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [0.36, 0.05, 0.22, 0.06], ...
    'CallBack', {@doneButton_cb, recipeSettingMain, obj, numOfReagent});

for i = 1:numOfReagent+5
    x = 0.05;
    if i <= numOfReagent
        reagent = obj.recipe.reagent{i};
        well = obj.recipe.well(i);
        time = obj.recipe.time(i);
        ri = obj.recipe.ri(i);
        velocity = obj.recipe.velocity(i);
        temp = obj.recipe.temp(i);
        comment = obj.recipe.comment{i};
    else
        reagent = '';
        well = '';
        time = '';
        ri = '';
        velocity = '';
        temp = '';
        comment = '';
    end
    
    reagentNames(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', reagent, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 1.5*w, h-0.01], ...
        'CallBack', {@changeReagents, obj, i});
    
    x = x+1.5*w+0.01;
    wellNums(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', well, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 0.8*w, h-0.01], ...
        'CallBack', {@changeWell, obj, i});
    
    x = x+0.8*w+0.01;
    timeValue(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', time, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 1.2*w, h-0.01], ...
        'CallBack', {@changeTime, obj, i});
    
    x = x+1.2*w+0.01;
    RIValue(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', ri, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 0.8*w, h-0.01], ...
        'CallBack', {@changeRI, obj, i});
    
    x = x+0.8*w+0.01;
    velocityValue(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', velocity, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, w, h-0.01], ...
        'CallBack', {@changeVelocity, obj, i});
    
    x = x+w+0.01;
    tempValue(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', temp, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 1.1*w, h-0.01], ...
        'CallBack', {@changeTemp, obj, i});
    
    x = x+1.1*w+0.01;
    commentText(i) = uicontrol(...
        'Parent', recipeSettingMain, ...
        'Style', 'edit', ...
        'String', comment, ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [x, 0.91 - h*i, 2.2*w, h-0.01], ...
        'CallBack', {@changeComment, obj, i});
end

movegui(recipeSettingMain, 'center');
set(recipeSettingMain, 'Visible', 'on');
uiwait(recipeSettingMain);
end

function changeReagents(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    reagentName = get(hObject, 'String');
    if index <= numOfReagent
        obj.recipe.reagent{index} = reagentName;
    else
        obj.recipe.reagent{end+1} = reagentName;
    end
end

function changeWell(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    wellNum = str2double(get(hObject, 'String'));
    if index <= numOfReagent
        obj.recipe.well(index) = wellNum;
    else
        obj.recipe.well(end+1) = wellNum;
    end
end

function changeTime(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    timeValue = str2double(get(hObject, 'String'));
    if index <= numOfReagent
        obj.recipe.time(index) = timeValue;
    else
        obj.recipe.time(end+1) = timeValue;
    end
end

function changeRI(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    RI = str2double(get(hObject, 'String'));
    if index <= numOfReagent
        obj.recipe.ri(index) = RI;
    else
        obj.recipe.ri(end+1) = RI;
    end
end

function changeVelocity(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    v = str2double(get(hObject, 'String'));
    if index <= numOfReagent
        obj.recipe.velocity(index) = v;
    else
        obj.recipe.velocity(end+1) = v;
    end
end

function changeTemp(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    temp = str2double(get(hObject, 'String'));
    if index <= numOfReagent
        obj.recipe.temp(index) = temp;
    else
        obj.recipe.temp(end+1) = temp;
    end
end

function changeComment(hObject, ~, obj, index)
    numOfReagent = length(obj.recipe.reagent);
    comment = get(hObject, 'String');
    if index <= numOfReagent
        obj.recipe.comment{index} = comment;
    else
        obj.recipe.comment{end+1} = comment;
    end
end

function doneButton_cb(~, ~, recipeSettingMain, obj, numOfReagent)
testPanel = panel_index('test');
recipeTable = obj.gui.panel(testPanel).assayUI.recipeTable;
for i = 1:numOfReagent
    recipeTable(:, 1) = num2cell(obj.recipe.time);
    recipeTable(:, 2) = obj.recipe.reagent;
    recipeTable(:, 3) = num2cell(obj.recipe.velocity);
    recipeTable(:, 4) = num2cell(obj.recipe.well);
    recipeTable(:, 5) = num2cell(obj.recipe.temp);
    recipeTable(:, 6) = num2cell(obj.recipe.ri);
    recipeTable(:, 7) = obj.recipe.comment;
    set(obj.gui.panel(testPanel).assayUI.recipeSummaryTable, ...
        'Data', ...
        recipeTable);
end
    close(recipeSettingMain);
end